# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.api.application_groups_api import ApplicationGroupsApi  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestApplicationGroupsApi(unittest.TestCase):
    """ApplicationGroupsApi unit test stubs"""

    def setUp(self):
        self.api = pyaxissecurity.api.application_groups_api.ApplicationGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_application_groups_create(self):
        """Test case for application_groups_create

        Create a New Application Group  # noqa: E501
        """
        pass

    def test_application_groups_delete(self):
        """Test case for application_groups_delete

        Delete Application Group by ID  # noqa: E501
        """
        pass

    def test_application_groups_get_by_id(self):
        """Test case for application_groups_get_by_id

        Get Application Group by ID  # noqa: E501
        """
        pass

    def test_application_groups_query(self):
        """Test case for application_groups_query

        Get Application Groups  # noqa: E501
        """
        pass

    def test_application_groups_update(self):
        """Test case for application_groups_update

        Update an Existing Application Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
