# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.ssl_exclusion_type import SslExclusionType  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestSslExclusionType(unittest.TestCase):
    """SslExclusionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSslExclusionType(self):
        """Test SslExclusionType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.ssl_exclusion_type.SslExclusionType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
