# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.paged_api_response_of_i_enumerable_of_connector_zone_model_v1 import PagedApiResponseOfIEnumerableOfConnectorZoneModelV1  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestPagedApiResponseOfIEnumerableOfConnectorZoneModelV1(unittest.TestCase):
    """PagedApiResponseOfIEnumerableOfConnectorZoneModelV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagedApiResponseOfIEnumerableOfConnectorZoneModelV1(self):
        """Test PagedApiResponseOfIEnumerableOfConnectorZoneModelV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.paged_api_response_of_i_enumerable_of_connector_zone_model_v1.PagedApiResponseOfIEnumerableOfConnectorZoneModelV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
