# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.swg_category_model_v1 import SwgCategoryModelV1  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestSwgCategoryModelV1(unittest.TestCase):
    """SwgCategoryModelV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwgCategoryModelV1(self):
        """Test SwgCategoryModelV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.swg_category_model_v1.SwgCategoryModelV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
