# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.api.groups_api import GroupsApi  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = pyaxissecurity.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_create(self):
        """Test case for groups_create

        Create a New Group  # noqa: E501
        """
        pass

    def test_groups_delete(self):
        """Test case for groups_delete

        Delete Group by ID  # noqa: E501
        """
        pass

    def test_groups_get_by_id(self):
        """Test case for groups_get_by_id

        Get Group by ID  # noqa: E501
        """
        pass

    def test_groups_query(self):
        """Test case for groups_query

        Get Groups  # noqa: E501
        """
        pass

    def test_groups_update(self):
        """Test case for groups_update

        Update an Existing Group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
