# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.swg_category_type import SwgCategoryType  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestSwgCategoryType(unittest.TestCase):
    """SwgCategoryType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwgCategoryType(self):
        """Test SwgCategoryType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.swg_category_type.SwgCategoryType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
