# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.api.swg_category_api import SwgCategoryApi  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestSwgCategoryApi(unittest.TestCase):
    """SwgCategoryApi unit test stubs"""

    def setUp(self):
        self.api = pyaxissecurity.api.swg_category_api.SwgCategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swg_category_create(self):
        """Test case for swg_category_create

        Create a New Web Category  # noqa: E501
        """
        pass

    def test_swg_category_delete(self):
        """Test case for swg_category_delete

        Delete Web Category by ID  # noqa: E501
        """
        pass

    def test_swg_category_get_by_id(self):
        """Test case for swg_category_get_by_id

        Get Web Category by ID  # noqa: E501
        """
        pass

    def test_swg_category_query(self):
        """Test case for swg_category_query

        Get Web Categories  # noqa: E501
        """
        pass

    def test_swg_category_update(self):
        """Test case for swg_category_update

        Update an Existing Web Category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
