# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.connector_status import ConnectorStatus  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestConnectorStatus(unittest.TestCase):
    """ConnectorStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorStatus(self):
        """Test ConnectorStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.connector_status.ConnectorStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
