# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.api.connectors_api import ConnectorsApi  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestConnectorsApi(unittest.TestCase):
    """ConnectorsApi unit test stubs"""

    def setUp(self):
        self.api = pyaxissecurity.api.connectors_api.ConnectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_connectors_create(self):
        """Test case for connectors_create

        Create a New Connector  # noqa: E501
        """
        pass

    def test_connectors_delete(self):
        """Test case for connectors_delete

        Delete Connector by ID  # noqa: E501
        """
        pass

    def test_connectors_get_by_id(self):
        """Test case for connectors_get_by_id

        Get Connector by ID  # noqa: E501
        """
        pass

    def test_connectors_query(self):
        """Test case for connectors_query

        Get Connectors  # noqa: E501
        """
        pass

    def test_connectors_regenerate(self):
        """Test case for connectors_regenerate

        Regenerate an Installation Command for an Exisitng Connector  # noqa: E501
        """
        pass

    def test_connectors_status(self):
        """Test case for connectors_status

        Get the Status of a Connector  # noqa: E501
        """
        pass

    def test_connectors_update(self):
        """Test case for connectors_update

        Update an Existing Connector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
