# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.api.applications_api import ApplicationsApi  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = pyaxissecurity.api.applications_api.ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applications_create(self):
        """Test case for applications_create

        Create a New Application  # noqa: E501
        """
        pass

    def test_applications_delete(self):
        """Test case for applications_delete

        Delete Application by ID  # noqa: E501
        """
        pass

    def test_applications_get_by_id(self):
        """Test case for applications_get_by_id

        Get Application by ID  # noqa: E501
        """
        pass

    def test_applications_query(self):
        """Test case for applications_query

        Get Applications  # noqa: E501
        """
        pass

    def test_applications_update(self):
        """Test case for applications_update

        Update an Existing Application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
