# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.application_model_v1_type import ApplicationModelV1Type  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestApplicationModelV1Type(unittest.TestCase):
    """ApplicationModelV1Type unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationModelV1Type(self):
        """Test ApplicationModelV1Type"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.application_model_v1_type.ApplicationModelV1Type()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
