# coding: utf-8

"""
    PublicAdminApi

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyaxissecurity
from pyaxissecurity.models.description_named_model_base import DescriptionNamedModelBase  # noqa: E501
from pyaxissecurity.rest import ApiException


class TestDescriptionNamedModelBase(unittest.TestCase):
    """DescriptionNamedModelBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDescriptionNamedModelBase(self):
        """Test DescriptionNamedModelBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyaxissecurity.models.description_named_model_base.DescriptionNamedModelBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
